### ISSUE TITLE
Add demo on codesandbox.io?

### ISSUE THREAD

**Issue by cowchimp** [trainline/react-skeletor#1]
Is it possible to link to a demo from the Readme?
Will help to understand the value proposition and usage.
Thanks!

**Comment by alex3165** [comment]
Hey @cowchimp, I have added a link to the demo up on Github page. Do you think it is enough?

See: https://trainline.github.io/react-skeletor/

**Comment by cowchimp** [comment]
Very cool.
Thank you.

Consider making the "Demo" link in the Readme direct to the "Examples" page, not the "Home" page.
(my reasoning is that one could click the "Demo" link expecting to see a demo, land on a page with the code snippet, and not notice the "Examples" link)
