### ISSUE TITLE
Any examples using with Redux?

### ISSUE THREAD

**Issue by sjdweb** [trainline/react-skeletor#7]
As above, any examples where the HOC (`createSkeletonProvider`) is wrapped in a `connect()` perhaps? 

My component will dispatch during componentWillMount if the data is not present, which doesn't seem compatible with dummyData method.

**Comment by sjdweb** [comment]
Just to update this, the key is making sure dummyData does not overwrite your props from `connect()`. This does mean in Typescript you would need those properties to be nullable. But I was able to get the proper values through to the component this way.

**Comment by adesurirey** [comment]
@sjdweb could you share your example redux example ?
